/**
 * generated by Xtext 2.15.0
 */
package com.altran.ide;

import com.altran.OptimindRuntimeModule;
import com.altran.OptimindStandaloneSetup;
import com.altran.ide.OptimindIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class OptimindIdeSetup extends OptimindStandaloneSetup {
  @Override
  public Injector createInjector() {
    OptimindRuntimeModule _optimindRuntimeModule = new OptimindRuntimeModule();
    OptimindIdeModule _optimindIdeModule = new OptimindIdeModule();
    return Guice.createInjector(Modules2.mixin(_optimindRuntimeModule, _optimindIdeModule));
  }
}
