/**
 * generated by Xtext 2.15.0
 */
package com.altran.ide;

import com.altran.ide.AbstractOptimindIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class OptimindIdeModule extends AbstractOptimindIdeModule {
}
