/*
 * generated by Xtext 2.16.0
 */
package com.altran.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractOptimindScopeProvider extends DelegatingScopeProvider {
}
