/*
 * generated by Xtext 2.15.0
 */
package com.altran.ide

import com.altran.OptimindRuntimeModule
import com.altran.OptimindStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class OptimindIdeSetup extends OptimindStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new OptimindRuntimeModule, new OptimindIdeModule))
	}
	
}
