/**
 * generated by Xtext 2.15.0
 */
package com.altran.scoping;

import com.altran.scoping.AbstractOptimindScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class OptimindScopeProvider extends AbstractOptimindScopeProvider {
}
