/**
 * generated by Xtext 2.15.0
 */
package com.altran;

import com.altran.OptimindStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class OptimindStandaloneSetup extends OptimindStandaloneSetupGenerated {
  public static void doSetup() {
    new OptimindStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
