/**
 * generated by Xtext 2.15.0
 */
package com.altran;

import com.altran.AbstractOptimindRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class OptimindRuntimeModule extends AbstractOptimindRuntimeModule {
}
