/**
 * generated by Xtext 2.15.0
 */
package com.altran.ui.wizard;

import com.google.common.collect.Iterables;
import java.util.Collections;
import java.util.List;
import org.eclipse.core.runtime.IStatus;
import org.eclipse.core.runtime.Status;
import org.eclipse.jdt.core.JavaCore;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.ui.XtextProjectHelper;
import org.eclipse.xtext.ui.util.PluginProjectFactory;
import org.eclipse.xtext.ui.wizard.template.AbstractProjectTemplate;
import org.eclipse.xtext.ui.wizard.template.BooleanTemplateVariable;
import org.eclipse.xtext.ui.wizard.template.GroupTemplateVariable;
import org.eclipse.xtext.ui.wizard.template.IProjectGenerator;
import org.eclipse.xtext.ui.wizard.template.ProjectTemplate;
import org.eclipse.xtext.ui.wizard.template.StringTemplateVariable;
import org.eclipse.xtext.xbase.lib.CollectionLiterals;
import org.eclipse.xtext.xbase.lib.ObjectExtensions;
import org.eclipse.xtext.xbase.lib.Procedures.Procedure1;

@ProjectTemplate(label = "Loop Workflow", icon = "project_template.png", description = "<p><b>Loop Workflow</b></p>\r\n<p>This is an example of loop usage in the workflow you can create with Optimind. It contains an example of a For Loop an a While Loop.</p>")
@SuppressWarnings("all")
public final class LoopProject extends AbstractProjectTemplate {
  private final BooleanTemplateVariable advanced = this.check("Advanced:", false);
  
  private final GroupTemplateVariable advancedGroup = this.group("Properties");
  
  private final StringTemplateVariable workflow = this.text("Workflow name:", "loopExample", this.advancedGroup);
  
  private final StringTemplateVariable path = this.text("Package:", "workflow", "The package path to place the files in", this.advancedGroup);
  
  @Override
  protected void updateVariables() {
    this.workflow.setEnabled(this.advanced.getValue());
    this.path.setEnabled(this.advanced.getValue());
    boolean _value = this.advanced.getValue();
    boolean _not = (!_value);
    if (_not) {
      this.workflow.setValue("loopExample");
      this.path.setValue("workflow");
    }
  }
  
  @Override
  protected IStatus validate() {
    Status _xifexpression = null;
    boolean _matches = this.path.getValue().matches("[a-z][a-z0-9_]*(/[a-z][a-z0-9_]*)*");
    if (_matches) {
      _xifexpression = null;
    } else {
      _xifexpression = new Status(IStatus.ERROR, "Wizard", (("\'" + this.path) + "\' is not a valid package name"));
    }
    return _xifexpression;
  }
  
  @Override
  public void generateProjects(final IProjectGenerator generator) {
    PluginProjectFactory _pluginProjectFactory = new PluginProjectFactory();
    final Procedure1<PluginProjectFactory> _function = (PluginProjectFactory it) -> {
      it.setProjectName(this.getProjectInfo().getProjectName());
      it.setLocation(this.getProjectInfo().getLocationPath());
      List<String> _projectNatures = it.getProjectNatures();
      Iterables.<String>addAll(_projectNatures, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList(JavaCore.NATURE_ID, "org.eclipse.pde.PluginNature", XtextProjectHelper.NATURE_ID)));
      List<String> _builderIds = it.getBuilderIds();
      Iterables.<String>addAll(_builderIds, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList(JavaCore.BUILDER_ID, XtextProjectHelper.BUILDER_ID)));
      List<String> _folders = it.getFolders();
      _folders.add("src");
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("src/");
      _builder.append(this.path);
      _builder.append("/");
      _builder.append(this.workflow);
      _builder.append(".optimind");
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Workflow loopExample {");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("Language Java");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("BaseTask principalBaseTask {");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("Task independantTask{");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("runner \"independantTask.java\"");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("}");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("BaseTask loopBaseTask {");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("Task task1 { ");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("Output map type File");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("Output flow type File");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("Output configuration type File  ");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("runner \"task1.java\"");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("}");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("Task task2 {");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("Connection map to \"task1.map\"");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("Connection flow to \"task1.flow\"");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("Connection testOutput to \"loopBaseTask.whileLoopExample.whileTask.whileLoopOutput\"");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("Output stats type File ");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("runner \"task2.java\"");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("}");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("Task task3 {");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("Connection stats to \"loopBaseTask.task2.stats\"");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("runner \"task3.java\"");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("}");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("While whileLoopExample{");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("condition \"testOutput.isEmpty() = true \"");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("do Task whileTask{");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t\t");
      _builder_1.append("Connection config to \"task1.configuration\"");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t\t");
      _builder_1.append("Output whileLoopOutput type File");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t\t");
      _builder_1.append("runner \"myTasks.java\"");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("}");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("}");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("For forLoopExample{");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("from 1");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("to 10");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("increment 2");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("do Task forLoopTask{");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t\t");
      _builder_1.append("runner \"forLoopTask.java\"");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("}");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("}");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t\t");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("If ifStatementExample{");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("condition \"[].isEmpty() = true\"");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("then Task ifStatementTask{");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t\t");
      _builder_1.append("runner \"ifStatementTask.java\"");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("}");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("}");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("}\t\t");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("}");
      _builder_1.newLine();
      _builder_1.append("}");
      _builder_1.newLine();
      this.addFile(it, _builder, _builder_1);
      StringConcatenation _builder_2 = new StringConcatenation();
      _builder_2.append("src/scripts/");
      _builder_2.append(this.workflow);
      _builder_2.append(".java");
      StringConcatenation _builder_3 = new StringConcatenation();
      _builder_3.append("\t\t\t");
      _builder_3.newLine();
      this.addFile(it, _builder_2, _builder_3);
    };
    PluginProjectFactory _doubleArrow = ObjectExtensions.<PluginProjectFactory>operator_doubleArrow(_pluginProjectFactory, _function);
    generator.generate(_doubleArrow);
  }
}
