/**
 * generated by xtext 2.15.0
 */
package com.altran.ui.wizard;

import com.altran.ui.wizard.EmptyWorkflow;
import com.altran.ui.wizard.HelloWorldFile;
import org.eclipse.xtext.ui.wizard.template.AbstractFileTemplate;
import org.eclipse.xtext.ui.wizard.template.IFileTemplateProvider;

/**
 * Create a list with all file templates to be shown in the template new file wizard.
 * 
 * Each template is able to generate one or more files.
 */
@SuppressWarnings("all")
public class OptimindFileTemplateProvider implements IFileTemplateProvider {
  @Override
  public AbstractFileTemplate[] getFileTemplates() {
    EmptyWorkflow _emptyWorkflow = new EmptyWorkflow();
    HelloWorldFile _helloWorldFile = new HelloWorldFile();
    return new AbstractFileTemplate[] { _emptyWorkflow, _helloWorldFile };
  }
}
