/**
 * generated by Xtext 2.15.0
 */
package com.altran.generator;

import com.altran.Utils.Utils;
import com.altran.generator.CustomTaskRunnerGenerator;
import com.altran.generator.LibraryFunctionGenerator;
import com.altran.generator.PythonCodeGenerator;
import com.altran.graphs.DotGraphGenerator;
import com.altran.optimind.model.workflow.Workflow;
import java.io.File;
import org.eclipse.core.resources.IFile;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Exceptions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class OptimindGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    try {
      Workflow workflow = this.getWorkflowFromResource(resource);
      String resourcePath = this.getResourceFilePath(resource);
      new DotGraphGenerator(resourcePath, workflow).createDotFile();
      String pythonFilePath = this.createPythonFilePath(resourcePath);
      new PythonCodeGenerator(workflow, pythonFilePath).generate();
      String scriptsPackagePath = this.createPackagePath(resourcePath);
      new LibraryFunctionGenerator(workflow, scriptsPackagePath).generate();
      new CustomTaskRunnerGenerator(workflow, scriptsPackagePath).generate();
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  public String createPackagePath(final String workflowFilePath) {
    String _xblockexpression = null;
    {
      String name = null;
      boolean _contains = workflowFilePath.contains("\\");
      if (_contains) {
        int last1 = workflowFilePath.lastIndexOf("\\");
        String name1 = workflowFilePath.substring(0, last1);
        int last = name1.lastIndexOf("\\");
        name = name1.substring(0, last);
      } else {
        name = workflowFilePath;
      }
      _xblockexpression = (name + "\\scripts\\");
    }
    return _xblockexpression;
  }
  
  public String getResourceFilePath(final Resource resource) {
    String _xblockexpression = null;
    {
      IFile ifile = Utils.getFile(resource);
      File file = ifile.getLocation().toFile();
      _xblockexpression = file.getPath();
    }
    return _xblockexpression;
  }
  
  public String createPythonFilePath(final String workflowFilePath) {
    String _xblockexpression = null;
    {
      String name = null;
      boolean _contains = workflowFilePath.contains(".");
      if (_contains) {
        int last = workflowFilePath.lastIndexOf(".");
        name = workflowFilePath.substring(0, last);
      } else {
        name = workflowFilePath;
      }
      _xblockexpression = (name + ".py");
    }
    return _xblockexpression;
  }
  
  public Workflow getWorkflowFromResource(final Resource resource) {
    EObject _get = resource.getContents().get(0);
    return ((Workflow) _get);
  }
}
