/**
 * generated by Xtext 2.15.0
 */
package com.altran.ui;

import com.altran.ui.AbstractOptimindUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class OptimindUiModule extends AbstractOptimindUiModule {
  public OptimindUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
